global:
  scrape_interval: 5s

scrape_configs:

  - job_name: "dapr-notification"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:9190"]

  - job_name: "dapr-payment"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:9191"]